server:
  port: 8888

spring:
  application:
    name: config-servie
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/native-repo
        git:
          uri: https://github.com/jongjin97/spring-cloud-config.git
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
